version: '3.8'

services:
  core_postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: creditdb
      POSTGRES_PASSWORD: creditdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info -P solo
    volumes:
      - .:/code
    depends_on:
      - redis

volumes:
  postgres_data: