# Generated by Django 5.0.1 on 2024-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('monthly_salary', models.FloatField()),
                ('approved_limit', models.IntegerField()),
                ('current_debt', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
